-- Scalable community directories, groups, inbox summaries, and private Realtime.

create extension if not exists pg_trgm with schema extensions;

create table public.community_areas (
  id bigint generated by default as identity primary key,
  city text not null,
  neighborhood text,
  state_code text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint community_areas_city_length
    check (char_length(btrim(city)) between 1 and 120),
  constraint community_areas_neighborhood_length
    check (neighborhood is null or char_length(btrim(neighborhood)) between 1 and 120),
  constraint community_areas_state_code
    check (state_code is null or state_code ~ '^[A-Z]{2}$')
);

create unique index community_areas_unique_location_idx
  on public.community_areas (
    lower(btrim(city)),
    lower(coalesce(nullif(btrim(neighborhood), ''), ''))
  );

create index community_areas_directory_idx
  on public.community_areas (is_active, city, neighborhood);

alter table public.community_areas enable row level security;
revoke all on table public.community_areas from anon, authenticated;
grant select on table public.community_areas to authenticated;

create policy "approved members view community areas"
on public.community_areas
for select
to authenticated
using (private.has_site_access() and is_active);

insert into public.community_areas (city, neighborhood, state_code)
values
  ('Michigan City', null, 'IN'),
  ('Michigan City', 'Downtown', 'IN'),
  ('La Porte', null, 'IN'),
  ('Long Beach', null, 'IN'),
  ('New Buffalo', null, 'MI'),
  ('Chicago', null, 'IL'),
  ('Chicago', 'Near West Side', 'IL')
on conflict do nothing;

insert into public.community_areas (city, neighborhood)
select distinct
  btrim(profile.city),
  nullif(btrim(profile.neighborhood), '')
from public.profiles profile
where nullif(btrim(profile.city), '') is not null
on conflict do nothing;

insert into public.community_areas (city, neighborhood)
select distinct btrim(profile.city), null
from public.profiles profile
where nullif(btrim(profile.city), '') is not null
on conflict do nothing;

create or replace function private.sync_profile_community_area()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if nullif(btrim(new.city), '') is not null then
    insert into public.community_areas (city, neighborhood)
    values (btrim(new.city), null)
    on conflict do nothing;

    if nullif(btrim(new.neighborhood), '') is not null then
      insert into public.community_areas (city, neighborhood)
      values (btrim(new.city), btrim(new.neighborhood))
      on conflict do nothing;
    end if;
  end if;
  return new;
end;
$$;

revoke all on function private.sync_profile_community_area() from public, anon, authenticated;

drop trigger if exists sync_profile_community_area on public.profiles;
create trigger sync_profile_community_area
  after insert or update of city, neighborhood on public.profiles
  for each row execute function private.sync_profile_community_area();

create table public.community_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null,
  emoji text not null default '🏘️',
  city text not null,
  neighborhood text,
  created_by uuid references public.profiles (id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_groups_name_length
    check (char_length(btrim(name)) between 3 and 80),
  constraint community_groups_description_length
    check (char_length(btrim(description)) between 5 and 300),
  constraint community_groups_emoji_length
    check (char_length(emoji) between 1 and 12),
  constraint community_groups_city_length
    check (char_length(btrim(city)) between 1 and 120),
  constraint community_groups_neighborhood_length
    check (neighborhood is null or char_length(btrim(neighborhood)) between 1 and 120)
);

create unique index community_groups_unique_name_area_idx
  on public.community_groups (
    lower(btrim(name)),
    lower(btrim(city)),
    lower(coalesce(nullif(btrim(neighborhood), ''), ''))
  )
  where is_active;

create index community_groups_area_created_idx
  on public.community_groups (
    lower(btrim(city)),
    lower(coalesce(nullif(btrim(neighborhood), ''), '')),
    created_at desc
  )
  where is_active;

alter table public.community_groups enable row level security;
revoke all on table public.community_groups from anon, authenticated;
grant select, insert, update, delete on table public.community_groups to authenticated;

create policy "approved members view active community groups"
on public.community_groups
for select
to authenticated
using (private.has_site_access() and is_active);

create policy "approved members create community groups"
on public.community_groups
for insert
to authenticated
with check (
  private.has_site_access()
  and created_by = (select auth.uid())
  and is_active
);

create policy "creators manage community groups"
on public.community_groups
for update
to authenticated
using (
  private.has_site_access()
  and (
    created_by = (select auth.uid())
    or exists (
      select 1 from public.site_admins admin
      where admin.user_id = (select auth.uid()) and admin.enabled
    )
  )
)
with check (
  private.has_site_access()
  and (
    created_by = (select auth.uid())
    or exists (
      select 1 from public.site_admins admin
      where admin.user_id = (select auth.uid()) and admin.enabled
    )
  )
);

create policy "creators remove community groups"
on public.community_groups
for delete
to authenticated
using (
  private.has_site_access()
  and (
    created_by = (select auth.uid())
    or exists (
      select 1 from public.site_admins admin
      where admin.user_id = (select auth.uid()) and admin.enabled
    )
  )
);

create table public.community_group_members (
  group_id uuid not null references public.community_groups (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create index community_group_members_user_joined_idx
  on public.community_group_members (user_id, joined_at desc);

alter table public.community_group_members enable row level security;
revoke all on table public.community_group_members from anon, authenticated;
grant select, insert, delete on table public.community_group_members to authenticated;

create policy "approved members view group memberships"
on public.community_group_members
for select
to authenticated
using (private.has_site_access());

create policy "approved members join groups"
on public.community_group_members
for insert
to authenticated
with check (
  private.has_site_access()
  and user_id = (select auth.uid())
  and exists (
    select 1 from public.community_groups community_group
    where community_group.id = group_id and community_group.is_active
  )
);

create policy "members leave groups"
on public.community_group_members
for delete
to authenticated
using (private.has_site_access() and user_id = (select auth.uid()));

insert into public.community_groups (name, description, emoji, city, neighborhood)
values
  ('Plant & Garden Club', 'Share gardening tips, seeds, cuttings, and local plant swaps.', '🪴', 'Michigan City', null),
  ('Local Pet Owners', 'Connect with nearby pet owners and share trusted local resources.', '🐾', 'Long Beach', null),
  ('DIY & Handyman', 'Share home improvement advice, project ideas, and local recommendations.', '🛠️', 'New Buffalo', null),
  ('Local News Watch', 'Discuss useful local updates and neighborhood announcements.', '📰', 'La Porte', null)
on conflict do nothing;

create or replace view public.community_groups_directory
with (security_invoker = true)
as
select
  community_group.id,
  community_group.name,
  community_group.description,
  community_group.emoji,
  community_group.city,
  community_group.neighborhood,
  community_group.created_by,
  community_group.is_active,
  community_group.created_at,
  count(group_member.user_id)::bigint as member_count
from public.community_groups community_group
left join public.community_group_members group_member
  on group_member.group_id = community_group.id
group by community_group.id;

revoke all on public.community_groups_directory from anon, authenticated;
grant select on public.community_groups_directory to authenticated;

create or replace function public.create_community_group(
  group_name text,
  group_description text,
  group_emoji text,
  group_city text,
  group_neighborhood text default null
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  created_group_id uuid;
begin
  if not private.has_site_access() or (select auth.uid()) is null then
    raise exception 'Approved membership is required';
  end if;

  insert into public.community_groups (
    name,
    description,
    emoji,
    city,
    neighborhood,
    created_by
  )
  values (
    btrim(group_name),
    btrim(group_description),
    coalesce(nullif(btrim(group_emoji), ''), '🏘️'),
    btrim(group_city),
    nullif(btrim(group_neighborhood), ''),
    (select auth.uid())
  )
  returning id into created_group_id;

  insert into public.community_group_members (group_id, user_id)
  values (created_group_id, (select auth.uid()));

  return created_group_id;
end;
$$;

revoke all on function public.create_community_group(text, text, text, text, text) from public, anon;
grant execute on function public.create_community_group(text, text, text, text, text) to authenticated;

create index if not exists posts_created_at_id_idx
  on public.posts (created_at desc, id desc);

create index if not exists posts_area_created_at_id_idx
  on public.posts (
    lower(coalesce(city, '')),
    lower(coalesce(neighborhood, '')),
    created_at desc,
    id desc
  );

create index if not exists profiles_full_name_trgm_idx
  on public.profiles using gin (full_name extensions.gin_trgm_ops);

create index if not exists business_profiles_business_name_trgm_idx
  on public.business_profiles using gin (business_name extensions.gin_trgm_ops);

create or replace function public.get_my_inbox()
returns table (
  other_user_id uuid,
  last_message_id uuid,
  last_sender_id uuid,
  last_recipient_id uuid,
  last_message_body text,
  last_message_read_at timestamptz,
  last_message_created_at timestamptz,
  unread_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  with visible_messages as (
    select
      message.id,
      message.sender_id,
      message.recipient_id,
      message.body,
      message.read_at,
      message.created_at,
      case
        when message.sender_id = (select auth.uid()) then message.recipient_id
        else message.sender_id
      end as other_user_id
    from public.direct_messages message
    where message.sender_id = (select auth.uid())
       or message.recipient_id = (select auth.uid())
  ), ranked_messages as (
    select
      visible_message.*,
      row_number() over (
        partition by visible_message.other_user_id
        order by visible_message.created_at desc, visible_message.id desc
      ) as message_rank,
      count(*) filter (
        where visible_message.recipient_id = (select auth.uid())
          and visible_message.read_at is null
      ) over (partition by visible_message.other_user_id) as unread_count
    from visible_messages visible_message
  )
  select
    ranked_message.other_user_id,
    ranked_message.id,
    ranked_message.sender_id,
    ranked_message.recipient_id,
    ranked_message.body,
    ranked_message.read_at,
    ranked_message.created_at,
    ranked_message.unread_count
  from ranked_messages ranked_message
  where ranked_message.message_rank = 1
  order by ranked_message.created_at desc, ranked_message.id desc;
$$;

revoke all on function public.get_my_inbox() from public, anon;
grant execute on function public.get_my_inbox() to authenticated;

-- Realtime private channels. Supabase permits policies on realtime.messages.
drop policy if exists "approved members receive neighborly realtime" on realtime.messages;
create policy "approved members receive neighborly realtime"
on realtime.messages
for select
to authenticated
using (
  private.has_site_access()
  and (
    realtime.topic() = 'neighborly:active'
    or realtime.topic() = 'user:' || (select auth.uid())::text || ':inbox'
  )
);

drop policy if exists "approved members send neighborly realtime" on realtime.messages;
create policy "approved members send neighborly realtime"
on realtime.messages
for insert
to authenticated
with check (
  private.has_site_access()
  and (
    realtime.topic() = 'neighborly:active'
    or realtime.topic() = 'user:' || (select auth.uid())::text || ':inbox'
  )
);

create or replace function private.broadcast_direct_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform realtime.send(
    jsonb_build_object(
      'id', new.id,
      'sender_id', new.sender_id,
      'recipient_id', new.recipient_id,
      'body', new.body,
      'read_at', new.read_at,
      'created_at', new.created_at
    ),
    'message_created',
    'user:' || new.recipient_id::text || ':inbox',
    true
  );
  return new;
end;
$$;

revoke all on function private.broadcast_direct_message() from public, anon, authenticated;

drop trigger if exists broadcast_direct_message on public.direct_messages;
create trigger broadcast_direct_message
  after insert on public.direct_messages
  for each row execute function private.broadcast_direct_message();

create or replace function private.broadcast_friendship_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  friendship_row public.friendships;
begin
  if tg_op = 'DELETE' then
    friendship_row := old;
  else
    friendship_row := new;
  end if;

  perform realtime.send(
    jsonb_build_object(
      'id', friendship_row.id,
      'requester_id', friendship_row.requester_id,
      'addressee_id', friendship_row.addressee_id,
      'status', friendship_row.status,
      'operation', tg_op
    ),
    'friendship_changed',
    'user:' || friendship_row.requester_id::text || ':inbox',
    true
  );

  perform realtime.send(
    jsonb_build_object(
      'id', friendship_row.id,
      'requester_id', friendship_row.requester_id,
      'addressee_id', friendship_row.addressee_id,
      'status', friendship_row.status,
      'operation', tg_op
    ),
    'friendship_changed',
    'user:' || friendship_row.addressee_id::text || ':inbox',
    true
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function private.broadcast_friendship_change() from public, anon, authenticated;

drop trigger if exists broadcast_friendship_change on public.friendships;
create trigger broadcast_friendship_change
  after insert or update or delete on public.friendships
  for each row execute function private.broadcast_friendship_change();
